# Generated by Django 5.0.6 on 2024-06-21 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_categoria_pedido_pedidozapatilla_pedido_zapatillas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapatilla',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplicacion.categoria'),
        ),
    ]
