# Generated by Django 5.0.6 on 2024-06-22 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_alter_zapatilla_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='direccion',
            name='region',
            field=models.CharField(default='Sin registrar', max_length=255),
        ),
        migrations.AlterField(
            model_name='zapatilla',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.modelo'),
        ),
        migrations.CreateModel(
            name='StockZapatilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.IntegerField()),
                ('cantidad', models.IntegerField(default=0)),
                ('zapatilla', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplicacion.zapatilla')),
            ],
        ),
    ]
