# Generated by Django 5.0.6 on 2024-06-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_modelo_direccion_region_alter_zapatilla_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapatilla',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Modelo',
        ),
    ]
