# Generated by Django 5.0.6 on 2024-07-03 00:10

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_usuario_is_staff_alter_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='talla',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(18)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidozapatilla',
            name='talla',
            field=models.IntegerField(default='7', validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(18)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidozapatilla',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(18)]),
        ),
    ]
