# Generated by Django 5.0.6 on 2024-06-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_remove_zapatilla_categoria_zapatilla_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockzapatilla',
            name='talla',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
