# Generated by Django 5.0.6 on 2024-06-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_alter_direccion_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='detalle',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
