# Generated by Django 5.0.6 on 2024-06-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_direccion_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='detalle',
            field=models.CharField(max_length=255, null=True, verbose_name='Detalle o departamento'),
        ),
    ]
