# Generated by Django 5.0.6 on 2024-06-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_alter_direccion_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(default=12345678),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='detalle',
            field=models.CharField(max_length=255, null=True, verbose_name='Detalle o Departamento'),
        ),
    ]
