# Generated by Django 5.0.6 on 2024-06-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0013_carrito_itemcarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
