# Generated by Django 5.0.6 on 2024-06-25 18:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0014_itemcarrito_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='zapatillas',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stockzapatilla',
            name='zapatilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.zapatilla'),
        ),
    ]
