# Generated by Django 5.0.6 on 2024-06-26 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0017_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
